### Hello

GET http://localhost:3000


### Cadastrar aluno

POST http://localhost:3000/alunos
Content-Type: application/json

{
    "nome": "Maria",
    "endereco": "teste",
    "telefone": "1234",
    "email": "teste@email.com",
    "anoNascimento": 2002,
    "xuxu": "xuxu"

}